# Generated by Django 5.0 on 2023-12-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.CharField(blank=True, max_length=15, null=True)),
                ('phones', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, max_length=15, null=True)),
                ('about_us', models.TextField(max_length=500)),
                ('street', models.TextField(max_length=20)),
                ('post_code', models.IntegerField(default=1)),
                ('city', models.TextField(max_length=20)),
            ],
        ),
    ]
