# Generated by Django 5.0 on 2023-12-25 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='description',
            field=models.TextField(default='very good production', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fruit',
            name='type',
            field=models.CharField(choices=[('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Bread', 'Bread'), ('Meat', 'Meat')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fruit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_fruit', to=settings.AUTH_USER_MODEL),
        ),
    ]
