# Generated by Django 5.0 on 2023-12-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0002_fruit_description_fruit_type_fruit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='description',
            field=models.TextField(default='very good production', max_length=300),
        ),
    ]
